export const LOAD_GAMES_SUCCESS = 'LOAD_GAMES_SUCCESS';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const UPDATE_GAME_SUCCESS = 'UPDATE_GAME_SUCCESS';

export const LOAD_COMPANIES_SUCCESS = 'LOAD_COMPANIES_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOGIN_AUTHENTICATED = 'LOGIN_AUTHENTICATED';
export const LOGIN_REFUSED = 'LOGIN_REFUSED';

export const LOAD_REGISTRATION_SUCCESS = 'LOAD_REGISTRATION_SUCCESS';
export const CREATE_REGISTRATION_SUCCESS = 'CREATE_REGISTRATION_SUCCESS';
export const UPDATE_REGISTRATION_SUCCESS = 'UPDATE_REGISTRATION_SUCCESS';

export const LOAD_PRIZES_SUCCESS = 'LOAD_PRIZES_SUCCESS';
export const CREATE_PRIZE_SUCCESS = 'CREATE_PRIZE_SUCCESS';
export const UPDATE_PRIZE_SUCCESS = 'UPDATE_PRIZE_SUCCESS';

export const LOAD_SPONSORS_SUCCESS = 'LOAD_SPONSORS_SUCCESS';
export const CREATE_SPONSOR_SUCCESS = 'CREATE_SPONSOR_SUCCESS';
export const UPDATE_SPONSOR_SUCCESS = 'UPDATE_SPONSOR_SUCCESS';

export const LOAD_PENDING_GAMES_SUCCESS = 'LOAD_PENDING_GAMES_SUCCESS';
export const CREATE_PENDING_GAMES_SUCCESS = 'CREATE_PENDING_GAMES_SUCCESS';
export const UPDATE_PENDING_GAMES_SUCCESS = 'UPDATE_PENDING_GAMES_SUCCESS';
