export const LOAD_GAMES_SUCCESS = 'LOAD_GAMES_SUCCESS';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const UPDATE_GAME_SUCCESS = 'UPDATE_GAME_SUCCESS';

export const LOAD_COMPANIES_SUCCESS = 'LOAD_COMPANIES_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOGIN_AUTHENTICATED = 'LOGIN_AUTHENTICATED';
export const LOGIN_REFUSED = 'LOGIN_REFUSED';

export const LOAD_REGISTRATION_SUCCESS = 'LOAD_REGISTRATION_SUCCESS';
export const CREATE_REGISTRATION_SUCCESS = 'CREATE_REGISTRATION_SUCCESS';
export const UPDATE_REGISTRATION_SUCCESS = 'UPDATE_REGISTRATION_SUCCESS';

