export const LOAD_GAMES_SUCCESS = 'LOAD_GAMES_SUCCESS';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const UPDATE_GAME_SUCCESS = 'UPDATE_GAME_SUCCESS';

export const LOAD_COMPANIES_SUCCESS = 'LOAD_COMPANIES_SUCCESS';
